image: elixir:1.5.1

services:
  - postgres:latest

variables:
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  MIX_ENV: test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

lint:
  script: mix credo

coverage:
  script:
    - mix ecto.create
    - mix ecto.migrate
    - mix coveralls
