apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serv
    spec:
      containers:
        - name: serv
          image: gcr.io/serv-179106/serv:8109acf63e2223176b708467267fca31cdf1bff4
          ports:
            - containerPort: 4000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SERV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: serv-admin-password
                  key: password
        - name: zipkin
          image: gcr.io/stackdriver-trace-docker/zipkin-collector
          ports:
            - containerPort: 9411
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.09
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=serv-179106:us-central1:serv-assets=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
